name: Hexo Deploy

on:
  push:
    branches: 
      - source

env:
  TZ: Asia/Shanghai
  GIT_USER: Vitan
  GIT_EMAIL: vitan.me@gmail.com
  DEPLOY_REPO: ivitan/ivitan.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Setup OS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout Repository source branch
        uses: actions/checkout@v2
        with:
          ref: source

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      
      - name: Setup Deploy Private Key
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Git Infomation
        run: | 
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Setup Hexo Dependencies
        run: |
          sudo timedatectl set-timezone $TZ
          npm install hexo-cli -g
          npm install
          wget https://github.com/ivitan/ivitan.github.io/releases/download/Pin/generator.js -O ./node_modules/hexo-generator-index/lib/generator.js

      - name: Deploy Hexo blog
        run: |
          hexo clean
          hexo deploy