name: Hexo Deploy

# 触发条件
on:
  push:
    branches: 
      - source

jobs:
  build: 
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: auto deploy
    
    steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@master
      with:
        node-version: "18.x"

    - name: Checkout Repository source branch
      uses: actions/checkout@v2
      with:
        ref: source

    - name: Generate Public Files
      run: |
        npm i
        npm install hexo-cli -g
        hexo clean && hexo generate

    - name: Deploy Hexo
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        external_repository: ivitan/ivitan.github.io
        publish_branch: master
        publish_dir: ./public
        commit_message: ${{ github.event.head_commit.message }}
        user_name: 'Vitan'

        user_email: 'vitan.me@gmail.com'
